### ISSUE TITLE
namespace in demo 30

### ISSUE THREAD

**Issue by choper725** [oblomov-dev/abap2UI5#177]
why the ns = ‘f’ is there in the dynamic page layout in Z2UI5_CL_APP_DEMO_30 ?

**Comment by oblomov-dev** [comment]
The namespace of the control is defined with f.

Check for example this control: sap.f.DynamicPageHeader
https://sapui5.hana.ondemand.com/#/api/sap.f.DynamicPageHeader

and sap.f is mapped to f here:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/102328295/232114296-29729d2a-0f6f-4da2-b881-e6277c420f7b.png">

Most of the times no ns is needed because most of the controls are part of the m library and m is mapped as the default namespace and can be used without extra naming it.

**Comment by choper725** [comment]
i see, so with that said, Object page layout should have ns = ‘uxap’ ?

**Comment by choper725** [comment]
dynamic page layout ia not only in sap.f namespace ?

**Comment by oblomov-dev** [comment]
dynamic page is but check heading or snapped content, they heave uxap and f.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/102328295/232143722-6bbd3e1c-6698-4619-bdbf-fd7473107419.png">

**Comment by choper725** [comment]
ohh i see, as a couple of classes serve object page layout and dynamic page, you must indicate sap.f as default it uxap.

might worth thinking of seperating in the future as just my cup of tea, this project is for abapers, and should be fairly simple and intuative, rather thantrying to figure out why ns is used sometimes, when 95% of the controls dont

**Comment by oblomov-dev** [comment]
yes i also discovered this situation last week for the first time, this is very rare!

made a small change now for consistence. you have to import now the ns in any case when using this rare controls which exists in more than one library. 

yes abapers who don't now the view definition logic of ui5 will be very confused, but i want to make the class cl_xml_view very technical and generic to make it usable for a wide range of future (more abap friendly) wrappers. maybe i can develop an abaper friendly wrapper class which makes it possible to display tables with just one method call like cl_salv_table did on top of this view class, but we will see!

**Comment by choper725** [comment]
thanks for your fast support

**Comment by oblomov-dev** [comment]
i close this issue, just open a new one if you find more things which are unclear etc.
