### ISSUE TITLE
On-premise Compatibility

### ISSUE THREAD

**Issue by mbtools** [oblomov-dev/abap2ui5#4]
Thanks for putting this creative solution together 👍 

And thank you for making it open source 🙏 🔝 

## Object Types / Branches

I'm trying to install it on the ABAP Developer Edition (docker) which is 7.54 - the on-premise scenario. In general, this can not work with the same repository as a BTP / cloud solution since there are object types that do not exist on-premise (in this case HTTP, SCO2, SIA6):

![image](https://user-images.githubusercontent.com/59966492/214027277-74140b64-efbc-4df9-9a12-8c6dade3f2a0.png)

My suggestion would be to create a new `on-prem` branch that does not include these objects. 

Having separate branches really helps to keep things in order.  You can still develop everything together in one system but just pay attention which object needs to be pushed to which branch. I would do three branches: 
- `main` all objects (current repo)
- `cloud` (everything + HTTP, SCO2, SIA6 + z2ui5_cl_http_cloud)
- `on-prem` (everything + SICF + z2ui5_cl_http_onprem)

Users can then install from the `cloud` or `on-prem` branches without any issues.

## Diffs

After the initial pull, there are a few diffs:

![image](https://user-images.githubusercontent.com/59966492/214028299-36be6857-4f2c-4b57-9136-0356b7b56b2c.png)

### DEVC

It looks like you developed using a package in the SAP namespace (which has `tpclass = X`). On-premise custom developments do not set this flag. I'm not sure if you can move to a local package ($) and update the repo from there which should remove the `tpclass` field. If not, remove the field in the `on-prem` branch.

![image](https://user-images.githubusercontent.com/59966492/214028617-b4a86aa1-9c81-42b8-9f6d-6aa2452e10db.png)

### TABL

On-prem abapGit does not serialize the ABAP language version. Remove the field in the `on-prem` branch.

![image](https://user-images.githubusercontent.com/59966492/214028866-76a13c57-70d8-4740-ab00-b1dd328dcdc0.png)

### CLAS

The class file should have an empty line at the end. Add it in the `on-prem` branch.

![image](https://user-images.githubusercontent.com/59966492/214028965-0f86fd36-d915-41b2-94f1-50bcaf23b829.png)

## Syntax errors

`CL_ABAP_RANGE` is missing but see from your blog that you are already working on this :-)

## Design

Your "lodash" class is quite a curious collection of things. Mixing functional methods into an exception class should really not be done.  It's very confusing. You're not using much of this utility class anyway. Maybe keep what you really use in a separate class from the exception ;-)

Anyway, great work already and I'm looking forward to the 'cl_abap_range' replacement so I can test the complete solution

**Comment by nomssi** [comment]
Is it even possible via a simple ASSIGN ... TO <fs> ? 
check https://blogs.sap.com/2021/10/19/new-kinds-of-abap-expressions/

**Comment by oblomov-dev** [comment]
Hello together! 

Thanks for the information and your time checking this project!

Normally I only work on customer systems, it is my first time publishing development to the community and also working with git with more than one person. I do my best to become more familiar with git as soon as possible, your help is always welcome! :)

@mbtools 
Thanks a lot for your detailed information!

**BRANCH**
I was always struggling when I tested the project in an on-prem system. The idea of different branches is very good! I updated the folder structure that there is one folder for the http on-prem artifacts and one folder for the http cloud artifacts. Each branch then only gets one of this folders. I updated the git project and hope this is what you need now.

**ON_PREM SYSTEM** 
Unfortunately I have no access to an on-prem system anymore at the moment. I only tested the project with an on-prem abap2022 stack a while ago and it was no problem. I made the corrections you recommended. No tpclass, empty line in the end of the class and deleted the abap language version. Because there is no ABAP Developer Edition anymore I made this changes with visual code and I have no chance to test it. If you have some time maybe you can do a quick check? Let me know what I have to change, I will support you as much as I can!

**OLD SYNTAX**
Yes there is still some work to do! I fixed now the cl_abap_range and the ref #( with dynamic assign syntax. Maybe it is working now on a 7.54 system? Let me know if there are still changes to do and I will fix them. Later I can also make the project compatible to more older releases. Unfortunately I have to replace all the new language features.

**DESIGN**
Oh yes, you are completely right! This utility class is very very messy, but my tool to make abap a little bit more easy to use. I will clean this up in the future and separate the exception from the rest.

@nomssi 
I replaced the dynamic ref syntax. Thanks for the link. What do you mean with „A copy of the exception class CX_ABAP_RANGE_CONV is needed“ ? Let me know if you need further changes.

Thanks again to both of you and let me know if you have further ideas and wishes.

Greetings.

**Comment by nomssi** [comment]
@oblomov-dev 
I got he first version to compile and run on the developer edition, but it was messy. The list of changes here is probably not complete. I will try to merge the changes with your newer version and publish a  fork, so you can check. 



I changed the classes Z2UI5_CL_HTTP_ONPREM, Z2UI5_CL_HLP_UTILITY, Z2UI5_CL_HTTP_HANDLER,  Z2UI5_CL_HLP_TREE_JSON. 

Everywhere the exception class CX_ABAP_RANGE_CONV was used, I replaced it with a local copy because it is not defined in the  Developer Edition.

I commented out all routines that use XCO_CP_JSON (TRANS_DATA_2_JSON, TRANS_JSON_2_DATA), as it is not available in the Developer Edition.

I had to downport many instances of the direct access to data references, e.g.

```
    DATA(lr_data) = REF #( object->(lv_attri) ).  "<<< not supported on lower releases
    CREATE DATA r_result LIKE lr_data->*.
    r_result->* = lr_data->*.
```
by

```
    FIELD-SYMBOLS <attribute> TYPE any.
    FIELD-SYMBOLS <result> TYPE any.

    DATA(lv_name) = |OBJECT->{ to_upper( attri_name ) }|.
    ASSIGN (lv_name) TO <attribute>.

    CREATE DATA r_result LIKE <attribute>.
    ASSIGN r_result->* TO <result>.

    <result> = <attribute>.
```
or in TRANS_OBJECT_2_XML
```
  METHOD trans_object_2_xml.
    FIELD-SYMBOLS <object> TYPE any.
    ASSIGN object->* TO <object>.

    CALL TRANSFORMATION id
       SOURCE data = <object> "i_result->ms_db-data
       RESULT XML result
        OPTIONS data_refs = 'heap-or-create'.
```

My HLP_GET_JSON_AS_ABAP looks like this
```
  METHOD hlp_get_json_as_abap.
    FIELD-SYMBOLS <any> TYPE any.

    DATA(o_type_desc) = cl_abap_typedescr=>describe_by_data( co_data ).

    CASE o_type_desc->kind.
      WHEN cl_abap_typedescr=>kind_struct.

      WHEN cl_abap_typedescr=>kind_table.
        FIELD-SYMBOLS <output> TYPE table.
        FIELD-SYMBOLS <row> TYPE any.
        DATA lr_row TYPE REF TO data.

        CLEAR co_data.
        ASSIGN co_data TO <output>.

        FIELD-SYMBOLS <tab> TYPE table.
        ASSIGN i_mo_app_row2_abap->* TO <tab>.
        LOOP AT <tab> ASSIGNING <any>.
          "INSERT INITIAL LINE INTO TABLE co_data ASSIGNING FIELD-SYMBOL(<row>).

          CREATE DATA lr_row LIKE LINE OF <tab>.
          ASSIGN lr_row->* TO <row>.

          INSERT <row> INTO TABLE <output>.
          " move corresponding ?
          DO.
            DATA(lv_index) = sy-index.
            ASSIGN COMPONENT lv_index OF STRUCTURE <any> TO FIELD-SYMBOL(<field>).
            IF sy-subrc <> 0.
              EXIT.
            ENDIF.
            ASSIGN COMPONENT lv_index OF STRUCTURE <row> TO FIELD-SYMBOL(<field2>).
            <field2> = <field>.
          ENDDO.

        ENDLOOP.


      WHEN cl_abap_typedescr=>kind_class.

      WHEN cl_abap_typedescr=>kind_intf.

      WHEN cl_abap_typedescr=>kind_elem.

        ASSIGN i_mo_app_row2_abap->* TO <any>.
        co_data = <any>.
*        IF  o_type_desc->get_relative_name( ) = 'ABAP_BOOL'.
*          DATA(lv_value) = COND #(  WHEN i_mo_app_row2_abap = abap_true THEN `true` ELSE `false` ).
*          r_result = lv_value.
*          RETURN.
*        ENDIF.
*
*        r_result =  '"' && i_mo_app_row2_abap && '"'.


      WHEN cl_abap_typedescr=>kind_ref.
    ENDCASE.


  ENDMETHOD.
```

best regards,

Jacques

**Comment by larshp** [comment]
I'll add a few cents to this issue(there is too much in it already)

In abapGit and many other open source projects we do [static analysis](https://github.com/marketplace/abaplint) to ensure the consistency of the development, both syntax and use of objects. I dont think `object->(lv_attri)` is handled properly in abaplint, but its a bug that can be fixed.

Anyhow, then everyone opening pull requests will get early feedback.

Also note that it all works when editing files standalone in vscode using https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint

**Comment by nomssi** [comment]
This fork contains all my changes: https://github.com/nomssi/abap2ui5
It compiles but I am still expecting translation errors.

**Comment by mbtools** [comment]
This is not the typical GH issue, @larshp. More a temporary project collaboration room 😉 . Once it's working (on-prem), issues can and should be more specific of course

@nomssi one [xml](https://github.com/nomssi/abap2ui5/blob/main/src/01/01/z2ui5_cl_http_onprem.clas.xml) is not filled correctly and on 754 I get the following errors:

![image](https://user-images.githubusercontent.com/59966492/214825993-3a7abbcb-e1aa-4ebb-945a-4ea84ff28452.png)

`object->(attr)` is a 756 feature. 

Using your own class to process JSON and making it work is a waste of time. I recommend using https://github.com/sbcgua/ajson. It works with 702 and higher and is well tested. You can copy it into a package of your app or make it a dependency that has to be installed beforehand.

**Comment by oblomov-dev** [comment]
@larshp 
Oh, now i understand more and more the real value of your addons and tooling :) thanks a lot, i will try this out!

@nomssi 
I tested your fork on my abap cloud trial account. It still works fine, great job! @mbtools found some problems, when i can help somehow, let me know!

@mbtools
Yes i can't remember anymore why i build my own JSON serializer. Maybe ajson is not working with the reduced language scope in the cloud environment? Anyway I will check ajson again and try to replace my one to avoid redundancy. thanks for the hint.

**Comment by mbtools** [comment]
AJSON on ABAP Cloud (almost): https://github.com/sbcgua/ajson/issues/147

**Comment by oblomov-dev** [comment]
Ah that's the way it goes here, thanks! ;)

**Comment by nomssi** [comment]
I have released new version: https://github.com/nomssi/abap2ui5

@mbtools  
Your errors list mostly correlate with the changes I had already made. 

Anyway I have fixed one error and added the propagation of some exceptions,  notably the CX_UUID_ERROR on your list.

**Comment by mbtools** [comment]
I missed that you already created branches! It works well with the `on-prem` branch. 

![image](https://user-images.githubusercontent.com/59966492/214868949-a77a1b56-48f3-4210-ba84-f0ce07b1213d.png)

Minor syntax warning:

![image](https://user-images.githubusercontent.com/59966492/214869277-a14557ed-221e-49ba-9202-c2eb2a0acfc9.png)

Just change `method IF_MESSAGE~GET_TEXT.` to `method GET_TEXT.`

and... it works!

![image](https://user-images.githubusercontent.com/59966492/214869631-caca8c50-55f8-498d-9e99-d08d7cc58a7b.png)

![image](https://user-images.githubusercontent.com/59966492/214869704-202f0070-5c22-4122-9250-8ac21f4869ce.png)

Totally awesome, guys 🔥 👍

**Comment by mbtools** [comment]
@oblomov-dev @nomssi are you on twitter?

**Comment by nomssi** [comment]
@mbtools  - I am not on twitter.

**Comment by mbtools** [comment]
Np. Join our Slack at https://communityinviter.com/apps/abapgit/abap if you like

**Comment by oblomov-dev** [comment]
@nomssi 
Very nice, thanks a lot for your work!
I hope there will be an on-prem ABAPDevEdition again very soon!

@mbtools 
My twitter life just started ;) My name is "OblomovDev". 

So i can take the fork from @nomssi now and commit all his changes of the on-prem branch to the three branches of my repository right? Or is there still something todo before?

**Comment by mbtools** [comment]
Great. You have one follower already and a big thread mentioning you  😁 
https://twitter.com/marcfbe/status/1618644442835214336

**Comment by mbtools** [comment]
yes, you can merge these branches

**Comment by oblomov-dev** [comment]
Wow, thanks for advertising this solution, i retweeted it and i also follow you now :)

By the way:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/102328295/214896343-d0d05515-c43f-446f-9fe5-59b1e591c85e.png">
There is no need to include the interface if_serializable_object, because it is already included in the interface z2ui5_if_app:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/102328295/214896592-852fb69d-f6f0-4dcd-a5e1-6b375201e27b.png">
That saves you another line of abap code ;)

**Comment by mbtools** [comment]
true. se80 automatically adds it and i was too lazy to remove it

you still want to get the changes into your repo. you (or @nomssi) go to https://github.com/nomssi/abap2ui5/branches and create a PR from there to your repo. then you're all set and we can close this.

**Comment by oblomov-dev** [comment]
@nomssi already created a PR. i merged it. now the on-prem is ready to use with all the changes!

What is the correct way to bring the changes also to the main and cloud branch? Using another PR to main? And after that bring it to the cloud branch? Sorry for asking git beginners questions, maybe you just can give me a few keywords and i will google the rest.

**Comment by nomssi** [comment]
@oblomov-dev 
you do not need Pull Requests because you are the repository's owner/author. 
I (as a contributor) need to create a PR from a fork to submit any change to you for review/integration. 

1) So first select the branch in abapGit,
2) if needed, *pull* to download/merge the remote branch to update your system code, then make the change you need.
3) then you must *stage* to upload the newer version to github, making it available to all of us

**Comment by nomssi** [comment]
And IMHO the issue can be closed now, we can open new ones as needed.

**Comment by mbtools** [comment]
if you need help, feel free to reach out via our slack channel

**Comment by oblomov-dev** [comment]
@nomssi @mbtools thanks for your work and this little jumpstart! :)
