### ISSUE TITLE
Feature request: Text area - control cursor position

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#83]
I have  want to move the cursor to the last line (scroll down automatically) after adding new text to a textarea (or editor control).

**Comment by oblomov-dev** [comment]
good feature, i will take a look to it. 
maybe i can add client->set_focus() and client->set_scroll_position()

**Comment by oblomov-dev** [comment]
I added the functionality, you can try it out now. let me know if it fits your needs or you need something else.

You can find a demo app for scrolling and focus in the demo section, just copy&paste from the source code the functionality you need to your app.

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/102328295/224807630-ad6bf062-55c8-4ac7-b676-36cc8c934823.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/102328295/224808090-aff7b84a-c1f8-4551-b45e-64f2c01678df.png">

**Comment by oblomov-dev** [comment]
Thanks for refactoring! I included your changes and extended the scroll & focus function. Check the screenshots below, is this what you need?

Furthermore:
I had to make a lot of refactoring because i prepared abap2UI5 for displaying popups. A lot of coding changed. Also the main flow logic, but i think now it is a lot better to understand. I import now the object runtime to the view and client. The method calls become a lot more simple now. But I am not sure if we still need an extra interface and if we have the calling problem on lower release again. Maybe you can check this again. Thanks a lot for the help!

Screenshots:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/102328295/225611393-2ed6e728-f28a-4233-bef2-be2251d87eea.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/102328295/225611054-44df8e7b-e9ef-4a62-bc83-7b297aea0b7d.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/102328295/225611274-2232faa4-c86c-4ce0-8452-fcccd006bc9a.png">

**Comment by nomssi** [comment]
the good news, this release works on 7.54. 

the bad news: I can achieve the scroll to bottom effect in my use case:
1) I add some text to a text area programmatically 
2) I try to set the focus on the last line
The code looks like this:


          WHEN 'BUTTON_EVAL'.
                      DATA(response) = repl( screen-code_area ).
                      format_all( ).
                      reset( ).
                      client->set( focus = screen-console_area focus_pos = '9999999' ).
                      client->set( page_scroll_pos = '99999999' ).

**Comment by lars-sawyer** [comment]
Is the functionality of the demo app also not working on your system/browser? (z2ui5_cl_app_demo_22)

**Comment by oblomov-dev** [comment]
Is the functionality of the demo app also not working on your browser/system? (z2ui5_cl_app_demo_22)

**Comment by nomssi** [comment]
Indeed, the demo app has the same issue. I have edited the text and added more line to show the effect.
If I press scroll to bottom, I get this:
![image](https://user-images.githubusercontent.com/18452507/225728119-c1cf5e96-221e-43d4-8b3e-a3908ee5853d.png)

Actually, I want this:
![image](https://user-images.githubusercontent.com/18452507/225728273-3237a06c-b89c-47a8-b993-3ade150ee0a7.png)

**Comment by oblomov-dev** [comment]
Ah ok now i got your point. You don’t want to scroll only the page, in addition you also want to scroll a specific control. I will check this again.

**Comment by oblomov-dev** [comment]
Ok i changed the logic again, now you can give the input and text area control also an ID. They have to be unique. Then you can define with the set method the scroll position of this control. You can set the focus with the cursor values. 

Example is updated, you can try it out.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/102328295/226097499-4f522c37-4fff-4ec4-8d8f-f827439e92a5.png">

**Comment by oblomov-dev** [comment]
I am not completly sure about you use case, but maybe also the formatted text control is interesting for you:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/102328295/226170504-2cb57782-4feb-49d1-a633-b64ade35e716.png">

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/102328295/226170532-800781f0-5c77-4a61-8ebf-4ec3304bb950.png">

**Comment by nomssi** [comment]
Thanks, I will try it out. 
My next task is to implement an input that is not in a selection screen. I think it will be best in a popup.

**Comment by oblomov-dev** [comment]
good timing 😉 thank you for testing the new features!
