### ISSUE TITLE
Table Maintenance error

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#87]
On my Demosystem (7.54? Abap Platform 1909 On premise) the method /ui2/cl_json=>serialize( ) has no FORMAT_OUTPUT parameter, so there is a syntax error in Z2UI5_CL_APP_DEMO_13.
I could run the test after commenting out the parameter

            format_output    = abap_true

in method  get_json_by_table( ).

**Comment by oblomov-dev** [comment]
thanks for the hint again! 
i commented it out and updated the main branch.

unfortunately i have no chance to see this because i have only access to abap steampunk trial. i was sure that /ui2/cl_json is available but forgot to check the parameters. maybe i should start working only in pure abap and without any dependencies 😅
